// packages/renderer/test-apps/react-app/src/Notedown.tsx
import { notedownToHtml, getNotedownStyles, type RenderOptions } from "@notedown/renderer";
import { useEffect } from "react";

interface NotedownProps {
  source: string;
  className?: string;
  theme?: "light" | "dark" | "auto";
}

let styleElement: HTMLStyleElement | null = null;

function injectStyles(theme: "light" | "dark" | "auto" = "light") {
  if (!styleElement) {
    styleElement = document.createElement("style");
    styleElement.id = "notedown-styles";
    document.head.appendChild(styleElement);
  }
  styleElement.textContent = getNotedownStyles(theme);
}

export function Notedown({ source, className, theme = "light" }: NotedownProps) {
  useEffect(() => {
    injectStyles(theme);
  }, [theme]);

  const html = notedownToHtml(source, { theme });
  return (
    <div
      className={className}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

// packages/renderer/test-apps/svelte-app/src/Notedown.svelte
<script lang="ts">
  import { notedownToHtml, getNotedownStyles, type RenderOptions } from "@notedown/renderer";

  let { source, className = "", theme = "light" }: { source: string; className?: string; theme?: "light" | "dark" | "auto" } = $props();

  let html = $derived(notedownToHtml(source, { theme }));

  let styleElement: HTMLStyleElement | null = null;
  $effect(() => {
    if (!styleElement) {
      styleElement = document.createElement("style");
      styleElement.id = "notedown-styles";
      document.head.appendChild(styleElement);
    }
    styleElement.textContent = getNotedownStyles(theme);
  });
</script>

<div class={className}>
  {@html html}
</div>
